#############################################################################
# Makefile for building: protoshop
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  protoshop.pro
# Template: app
# Command: /home/ya_/Program/Qt/5.12.5/gcc_64/bin/qmake -o Makefile protoshop.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Program/Qt/5.12.5/gcc_64/include -I../../../Program/Qt/5.12.5/gcc_64/include/QtGui -I../../../Program/Qt/5.12.5/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../Program/Qt/5.12.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ya_/Program/Qt/5.12.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/ya_/Program/Qt/5.12.5/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/ya_/Program/Qt/5.12.5/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = protoshop1.0.0
DISTDIR = /home/ya_/Repo/kuliah/if4073-protoshop/bin/protoshop1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/ya_/Program/Qt/5.12.5/gcc_64/lib
LIBS          = $(SUBLIBS) -lpthread /home/ya_/Program/Qt/5.12.5/gcc_64/lib/libQt5Gui.so /home/ya_/Program/Qt/5.12.5/gcc_64/lib/libQt5Core.so -lGL -lXext -lX11 -lm  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/utils/string.cpp \
		src/utils/reader.cpp \
		src/main.cpp \
		src/image/base.cpp \
		src/image/pixel.cpp \
		src/image/b_w.cpp \
		src/image/r_g_b.cpp \
		src/image/grayscale.cpp \
		src/adjustment/inverse.cpp \
		src/adjustment/brighten.cpp \
		src/adjustment/grayscaling.cpp 
OBJECTS       = bin/string.o \
		bin/reader.o \
		bin/main.o \
		bin/base.o \
		bin/pixel.o \
		bin/b_w.o \
		bin/r_g_b.o \
		bin/grayscale.o \
		bin/inverse.o \
		bin/brighten.o \
		bin/grayscaling.o
DIST          = ../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/linux.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/qconfig.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/toolchain.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11inc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11lib.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resources.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/moc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/file_copies.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/lex.prf \
		protoshop.pro lib/CImg/CImg.h \
		src/utils/reader.hpp \
		src/utils/string.hpp \
		src/utils/exception.hpp \
		src/image/b_w.hpp \
		src/image/r_g_b.hpp \
		src/image/base.hpp \
		src/image/grayscale.hpp \
		src/image/pixel.hpp \
		src/image/image.hpp \
		src/image/exception.hpp \
		src/adjustment/adjustment.hpp \
		src/adjustment/brighten.hpp \
		src/adjustment/base.hpp \
		src/adjustment/inverse.hpp \
		src/adjustment/grayscaling.hpp src/utils/string.cpp \
		src/utils/reader.cpp \
		src/main.cpp \
		src/image/base.cpp \
		src/image/pixel.cpp \
		src/image/b_w.cpp \
		src/image/r_g_b.cpp \
		src/image/grayscale.cpp \
		src/adjustment/inverse.cpp \
		src/adjustment/brighten.cpp \
		src/adjustment/grayscaling.cpp
QMAKE_TARGET  = protoshop
DESTDIR       = 
TARGET        = protoshop


first: all
####### Build rules

protoshop:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: protoshop.pro ../../../Program/Qt/5.12.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/linux.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/qconfig.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/toolchain.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11inc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11lib.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resources.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/moc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/file_copies.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/lex.prf \
		protoshop.pro
	$(QMAKE) -o Makefile protoshop.pro
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_pre.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/unix.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/linux.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/sanitize.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-base.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/common/g++-unix.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/qconfig.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_functions.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt_config.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/toolchain.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_pre.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resolve_config.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/default_post.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/thread.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11inc.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/x11lib.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/warn_on.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qt.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/resources.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/moc.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/qmake_use.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/file_copies.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/exceptions.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/yacc.prf:
../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/lex.prf:
protoshop.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile protoshop.pro

qmake_all: FORCE


all: Makefile protoshop

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents lib/CImg/CImg.h src/utils/reader.hpp src/utils/string.hpp src/utils/exception.hpp src/image/b_w.hpp src/image/r_g_b.hpp src/image/base.hpp src/image/grayscale.hpp src/image/pixel.hpp src/image/image.hpp src/image/exception.hpp src/adjustment/adjustment.hpp src/adjustment/brighten.hpp src/adjustment/base.hpp src/adjustment/inverse.hpp src/adjustment/grayscaling.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/utils/string.cpp src/utils/reader.cpp src/main.cpp src/image/base.cpp src/image/pixel.cpp src/image/b_w.cpp src/image/r_g_b.cpp src/image/grayscale.cpp src/adjustment/inverse.cpp src/adjustment/brighten.cpp src/adjustment/grayscaling.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -D_REENTRANT -Wall -W -dM -E -o moc_predefs.h ../../../Program/Qt/5.12.5/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

bin/string.o: src/utils/string.cpp src/utils/string.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/string.o src/utils/string.cpp

bin/reader.o: src/utils/reader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/reader.o src/utils/reader.cpp

bin/main.o: src/main.cpp src/image/image.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp \
		src/image/grayscale.hpp \
		src/image/r_g_b.hpp \
		src/image/exception.hpp \
		src/utils/exception.hpp \
		src/adjustment/adjustment.hpp \
		src/adjustment/base.hpp \
		src/adjustment/inverse.hpp \
		src/adjustment/grayscaling.hpp \
		src/adjustment/brighten.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o src/main.cpp

bin/base.o: src/image/base.cpp lib/CImg/CImg.h \
		src/utils/string.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		src/image/pixel.hpp \
		src/image/exception.hpp \
		src/utils/exception.hpp \
		src/image/grayscale.hpp \
		src/image/r_g_b.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/base.o src/image/base.cpp

bin/pixel.o: src/image/pixel.cpp src/image/pixel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/pixel.o src/image/pixel.cpp

bin/b_w.o: src/image/b_w.cpp src/image/exception.hpp \
		src/utils/exception.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/b_w.o src/image/b_w.cpp

bin/r_g_b.o: src/image/r_g_b.cpp src/image/exception.hpp \
		src/utils/exception.hpp \
		src/utils/reader.hpp \
		src/image/r_g_b.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/r_g_b.o src/image/r_g_b.cpp

bin/grayscale.o: src/image/grayscale.cpp src/image/grayscale.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/grayscale.o src/image/grayscale.cpp

bin/inverse.o: src/adjustment/inverse.cpp src/adjustment/inverse.hpp \
		src/adjustment/base.hpp \
		src/image/image.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp \
		src/image/grayscale.hpp \
		src/image/r_g_b.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/inverse.o src/adjustment/inverse.cpp

bin/brighten.o: src/adjustment/brighten.cpp src/adjustment/brighten.hpp \
		src/adjustment/base.hpp \
		src/image/image.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp \
		src/image/grayscale.hpp \
		src/image/r_g_b.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/brighten.o src/adjustment/brighten.cpp

bin/grayscaling.o: src/adjustment/grayscaling.cpp src/adjustment/grayscaling.hpp \
		src/adjustment/base.hpp \
		src/image/image.hpp \
		src/image/b_w.hpp \
		src/image/base.hpp \
		lib/CImg/CImg.h \
		src/image/pixel.hpp \
		src/image/grayscale.hpp \
		src/image/r_g_b.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/grayscaling.o src/adjustment/grayscaling.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

